enum demo {
  express = "express",
  bodyParser = "body-parser",
  demoRouter = "./src/routes/demo.routes",
  moviesRouter = "./src/routes/movies.routes",
  userRouter = "./src/routes/user.routes",
  mongoose = "mongoose",
  Worker = "worker_threads",
  app = "app",
  port = 3000,
  secret = "secret",
  mongodb = "mongodb://localhost:27017/demo",
  blockRouter = "/block-router",
  startWorker = "/start-worker",
  worker = "./worker.js",
  message = "message",
  result = "result",
  start = "start",
  root = "/",
  echo = "/echo",
  hello = "Hello, world!",
  example = "Example app listening on port",
}
